#!/usr/bin/env python3
"""Run-2 first-iteration small-cluster search.

Blind search first; unblind only in output descriptions. Uses existing
`results/blind_model_feature_table.csv` generated by run_blind_grouping.py.

Implements:
- per-feature floor/ceiling discontinuity scan;
- full-block density-style small-cluster candidates using OPTICS/DBSCAN plus
  nearest-neighbour microcluster search;
- permutation significance (raw p) and Benjamini-Hochberg q;
- cross-source coherence by member-set Jaccard;
- human-readable cluster catalogue and residual report.

No new LLM/coder evaluations.
"""
from __future__ import annotations

import csv, math, random, statistics, itertools, json
from pathlib import Path
from collections import defaultdict, Counter

import numpy as np
from scipy.spatial.distance import pdist, squareform
from scipy.stats import spearmanr
from sklearn.cluster import OPTICS, DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'results'
FEATURE_TABLE = OUT / 'blind_model_feature_table.csv'
RANK_DIR = OUT / 'cluster_search'
RANDOM_SEED = 20260523
PERMUTATIONS = 1000
MIN_CLUSTER = 3
MAX_CLUSTER = 10
HEADLINE_Q = 0.05
HEADLINE_P = 0.01
WATCH_P = 0.05

BLOCKS = {
    'values_disclosure': ('A_',),
    'values_owned': ('B1_',),
    'values_non_owned': ('B2_',),
    'values_wishes': ('B3_',),
    'values_cross_surface': ('B4_',),
    'v1_markers': ('C_', 'v1_'),
    'freeflow_form': ('D_',),
    'posture': ('E_',),
}


def safe_float(x):
    try:
        if x is None or x == '': return None
        v = float(x)
        if math.isnan(v) or math.isinf(v): return None
        return v
    except Exception:
        return None


def read_rows():
    rows = list(csv.DictReader(FEATURE_TABLE.open(encoding='utf-8')))
    # Headline subset follows run 1: enough freeflow marker coverage.
    headline = [r for r in rows if (safe_float(r.get('C_v1_marker_samples_used')) or 0) >= 50]
    return rows, headline


def is_measure_column(c):
    if c == 'blind_id' or c.startswith('UNBLINDING_METADATA'):
        return False
    # Denominators / coverage / sample-count columns are audit metadata, not
    # personality differentiators. Including them creates spurious clusters such
    # as high-n collection cells.
    if (c.endswith('_n') or c.endswith('_n_valid') or c.endswith('_samples')
            or c.endswith('_samples_used') or c.endswith('_profile_samples')):
        return False
    if c in {'C_v1_marker_samples_used', 'D_freeflow_profile_samples',
             'E_posture_n', 'E_values_sample_n'}:
        return False
    return True


def numeric_columns(rows, min_coverage=0.7):
    cols=[]
    for c in rows[0].keys():
        if not is_measure_column(c): continue
        vals=[safe_float(r.get(c)) for r in rows]
        vals=[v for v in vals if v is not None]
        if len(vals) >= min_coverage * len(rows) and vals and max(vals)-min(vals) > 1e-12:
            cols.append(c)
    return cols


def block_columns(cols, block):
    pref = BLOCKS[block]
    return [c for c in cols if c.startswith(pref)]


def model_label(r):
    return r.get('UNBLINDING_METADATA_model') or r['blind_id']


def lab_label(r):
    return r.get('UNBLINDING_METADATA_lab') or ''


def fdr_bh(pvals):
    n=len(pvals)
    order=sorted(range(n), key=lambda i:pvals[i])
    q=[1.0]*n
    prev=1.0
    for rank,i in enumerate(reversed(order), start=1):
        # reversed rank: largest p first. Actual BH q = p*n/k.
        k=n-rank+1
        val=min(prev, pvals[i]*n/max(k,1))
        q[i]=min(val,1.0)
        prev=val
    return q


def write_csv(path, rows, fieldnames):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', newline='', encoding='utf-8') as f:
        w=csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        w.writeheader(); w.writerows(rows)


def discontinuity_scan(rows, cols):
    out=[]
    n_total=len(rows)
    for c in cols:
        vals=[]
        for r in rows:
            v=safe_float(r.get(c))
            if v is not None: vals.append((v,r))
        if len(vals) < 0.7*n_total: continue
        vals.sort(key=lambda x:x[0])
        xs=[v for v,r in vals]
        if len(set(xs)) < 3: continue
        sd=statistics.pstdev(xs) or 0.0
        gaps=[xs[i+1]-xs[i] for i in range(len(xs)-1)]
        nonzero=[g for g in gaps if g>1e-12]
        med_gap=statistics.median(nonzero) if nonzero else 0.0
        for side in ['floor','ceiling']:
            candidates=[]
            if side == 'floor':
                idxs=range(MIN_CLUSTER-1, min(MAX_CLUSTER, len(xs)-1)) # gap after idx
                for i in idxs:
                    gap=gaps[i]
                    size=i+1
                    members=[r['blind_id'] for v,r in vals[:size]]
                    models=[model_label(r) for v,r in vals[:size]]
                    candidates.append((gap,size,members,models,xs[i],xs[i+1]))
            else:
                idxs=range(max(0,len(xs)-MAX_CLUSTER-1), len(xs)-MIN_CLUSTER)
                for i in idxs: # gap after i, top size len-i-1
                    gap=gaps[i]
                    size=len(xs)-i-1
                    members=[r['blind_id'] for v,r in vals[i+1:]]
                    models=[model_label(r) for v,r in vals[i+1:]]
                    candidates.append((gap,size,members,models,xs[i+1],xs[i]))
            if not candidates: continue
            gap,size,members,models,boundary,neighbor=max(candidates, key=lambda x:(x[0], -x[1]))
            threshold_ok = gap >= sd or (med_gap > 0 and gap >= 2*med_gap)
            if MIN_CLUSTER <= size <= MAX_CLUSTER and threshold_ok and gap > 0:
                out.append({
                    'candidate_id': f'F{len(out)+1:04d}',
                    'source_type':'feature_discontinuity',
                    'block': next((b for b in BLOCKS if c.startswith(BLOCKS[b])), 'other'),
                    'feature': c,
                    'side': side,
                    'n_models': size,
                    'coverage_n': len(vals),
                    'gap': f'{gap:.9g}',
                    'column_sd': f'{sd:.9g}',
                    'median_nonzero_gap': f'{med_gap:.9g}',
                    'boundary_value': f'{boundary:.9g}',
                    'neighbor_value': f'{neighbor:.9g}',
                    'blind_ids': ';'.join(members),
                    'UNBLINDING_METADATA_models': ';'.join(models),
                })
    out.sort(key=lambda r: (-(float(r['gap'])/(float(r['column_sd']) or 1e-9)), r['feature'], r['side']))
    # reassign stable ids after sort
    for i,r in enumerate(out,1): r['candidate_id']=f'F{i:04d}'
    return out


def matrix_for(rows, cols, metric='euclidean'):
    # Median-impute within selected rows, z-standardize. Returns X and distance matrix.
    if not cols: return None, None, []
    use=[]
    arr=[]
    for c in cols:
        vals=[safe_float(r.get(c)) for r in rows]
        present=[v for v in vals if v is not None]
        if len(present) < 0.7*len(rows) or max(present)-min(present) <= 1e-12: continue
        use.append(c)
    if not use: return None, None, []
    for r in rows:
        row=[]
        for c in use:
            vals=[safe_float(rr.get(c)) for rr in rows]
            present=[v for v in vals if v is not None]
            med=statistics.median(present)
            row.append(safe_float(r.get(c)) if safe_float(r.get(c)) is not None else med)
        arr.append(row)
    X=np.array(arr, dtype=float)
    X=StandardScaler().fit_transform(X)
    if metric == 'euclidean':
        D=squareform(pdist(X, metric='euclidean'))
    elif metric == 'cosine':
        D=squareform(pdist(X, metric='cosine'))
        D=np.nan_to_num(D, nan=0.0, posinf=1.0, neginf=1.0)
    elif metric == 'spearman':
        # correlation distance over feature ranks; fallback for too few cols.
        if X.shape[1] < 2:
            D=squareform(pdist(X, metric='euclidean'))
        else:
            D=np.zeros((len(rows),len(rows)))
            ranks=np.apply_along_axis(lambda a: np.argsort(np.argsort(a)), 1, X)
            for i in range(len(rows)):
                for j in range(i+1,len(rows)):
                    rho=spearmanr(ranks[i], ranks[j]).statistic
                    if math.isnan(rho): rho=0.0
                    D[i,j]=D[j,i]=1-rho
    else:
        raise ValueError(metric)
    return X,D,use


def canonical_members(indices, rows):
    return tuple(sorted(rows[i]['blind_id'] for i in indices))


def density_candidates(rows, cols_by_block, metrics=('euclidean',)):
    candidates=[]
    for block, cols in cols_by_block.items():
        for metric in metrics:
            X,D,use=matrix_for(rows, cols, metric)
            if X is None or len(use) == 0: continue
            # OPTICS with several xi settings.
            for xi in [0.03, 0.05, 0.08, 0.12]:
                try:
                    labels=OPTICS(min_samples=2, min_cluster_size=MIN_CLUSTER, xi=xi, metric='precomputed').fit_predict(D)
                except Exception:
                    labels=np.array([-1]*len(rows))
                for lab in sorted(set(labels)):
                    if lab < 0: continue
                    idx=[i for i,l in enumerate(labels) if l==lab]
                    if MIN_CLUSTER <= len(idx) <= MAX_CLUSTER:
                        candidates.append({'source_type':'density_optics','block':block,'metric':metric,'method':f'OPTICS_xi={xi}','feature_count':len(use),'features':'|'.join(use[:25]),'indices':tuple(idx)})
            # DBSCAN over quantile eps values. This often catches tight islands OPTICS misses.
            tri=D[np.triu_indices_from(D,1)]
            tri=tri[tri>1e-12]
            for q in [0.03,0.05,0.08,0.10,0.15]:
                if len(tri)==0: continue
                eps=float(np.quantile(tri,q))
                try:
                    labels=DBSCAN(eps=eps, min_samples=2, metric='precomputed').fit_predict(D)
                except Exception:
                    labels=np.array([-1]*len(rows))
                for lab in sorted(set(labels)):
                    if lab < 0: continue
                    idx=[i for i,l in enumerate(labels) if l==lab]
                    if MIN_CLUSTER <= len(idx) <= MAX_CLUSTER:
                        candidates.append({'source_type':'density_dbscan','block':block,'metric':metric,'method':f'DBSCAN_q={q}', 'feature_count':len(use),'features':'|'.join(use[:25]),'indices':tuple(idx)})
            # KNN microclusters: for every seed, take k nearest neighbours incl seed.
            for k in range(MIN_CLUSTER, MAX_CLUSTER+1):
                for i in range(len(rows)):
                    idx=tuple(sorted(np.argsort(D[i])[:k].tolist()))
                    candidates.append({'source_type':'knn_microcluster','block':block,'metric':metric,'method':f'KNN_k={k}', 'feature_count':len(use),'features':'|'.join(use[:25]),'indices':idx})
    return candidates


def within_mean(D, idx):
    if len(idx)<2: return 0.0
    sub=D[np.ix_(idx,idx)]
    vals=sub[np.triu_indices_from(sub,1)]
    return float(vals.mean()) if len(vals) else 0.0


def significance_for_candidates(rows, candidates, cols_by_block):
    rng=random.Random(RANDOM_SEED)
    cache={}
    enriched=[]
    # Deduplicate exact source/member/method candidates first.
    seen=set()
    unique=[]
    for c in candidates:
        members=canonical_members(c['indices'], rows)
        key=(c['source_type'], c['block'], c.get('metric',''), c.get('method',''), members)
        if key in seen: continue
        seen.add(key); unique.append(c)
    for c in unique:
        block=c['block']; metric=c.get('metric','euclidean')
        key=(block,metric)
        if key not in cache:
            X,D,use=matrix_for(rows, cols_by_block[block], metric)
            cache[key]=(D,use)
        D,use=cache[key]
        if D is None: continue
        idx=list(c['indices']); k=len(idx)
        obs=within_mean(D, idx)
        le=0
        for _ in range(PERMUTATIONS):
            samp=rng.sample(range(len(rows)), k)
            if within_mean(D, samp) <= obs + 1e-12:
                le += 1
        p=(le+1)/(PERMUTATIONS+1)
        members=canonical_members(idx, rows)
        rdict={
            'candidate_id':'',
            'source_type':c['source_type'],
            'block':block,
            'metric':metric,
            'method':c.get('method',''),
            'n_models':k,
            'within_mean_distance':f'{obs:.9g}',
            'p_raw':p,
            'q_fdr':'',
            'feature_count':c.get('feature_count',len(use)),
            'features':c.get('features','|'.join(use[:25])),
            'blind_ids':';'.join(members),
            'UNBLINDING_METADATA_models':';'.join(model_label(rows[i]) for i in sorted(idx, key=lambda ii: rows[ii]['blind_id'])),
            'UNBLINDING_METADATA_labs':';'.join(lab_label(rows[i]) for i in sorted(idx, key=lambda ii: rows[ii]['blind_id'])),
        }
        enriched.append(rdict)
    qs=fdr_bh([r['p_raw'] for r in enriched]) if enriched else []
    for i,r in enumerate(enriched):
        r['q_fdr']=qs[i]
        
        if r.get('source_type') == 'knn_microcluster':
            r['status'] = 'support' if (r['p_raw'] < HEADLINE_P and qs[i] < HEADLINE_Q) else ('support_watch' if r['p_raw'] < WATCH_P else 'discard')
        else:
            r['status']='headline' if (r['p_raw'] < HEADLINE_P and qs[i] < HEADLINE_Q) else ('watchlist' if r['p_raw'] < WATCH_P else 'discard')
        r['p_raw']=f'{r["p_raw"]:.9g}'; r['q_fdr']=f'{r["q_fdr"]:.9g}'
    enriched.sort(key=lambda r:(r['status']!='headline', float(r['p_raw']), r['block'], r['blind_ids']))
    for i,r in enumerate(enriched,1): r['candidate_id']=f'C{i:04d}'
    return enriched


def cluster_key_members(r):
    return set((r.get('blind_ids') or '').split(';')) - {''}


def coherence(signif_rows, feature_rows):
    # Include feature discontinuities as recurrence evidence but not p-filtered headline clusters.
    all_rows=[]
    for r in signif_rows:
        if r['status'] in ('headline','watchlist','support','support_watch'):
            rr=dict(r); rr['catalogue_id']=r['candidate_id']; all_rows.append(rr)
    for r in feature_rows:
        rr=dict(r); rr['catalogue_id']=r['candidate_id']; rr['metric']='single_feature'; rr['method']=r['side']; rr['status']='feature_flag'; all_rows.append(rr)
    out=[]
    for r in all_rows:
        s=cluster_key_members(r)
        if not s: continue
        rec=[]
        blocks=set(); metrics=set(); source_types=set()
        for o in all_rows:
            so=cluster_key_members(o)
            if not so: continue
            jac=len(s&so)/len(s|so)
            if jac >= 0.7:
                rec.append(o['catalogue_id'])
                if o.get('block'): blocks.add(o.get('block'))
                if o.get('metric'): metrics.add(o.get('metric'))
                if o.get('source_type'): source_types.add(o.get('source_type'))
        out.append({
            'catalogue_id':r['catalogue_id'],
            'status':r.get('status',''),
            'block':r.get('block',''),
            'metric':r.get('metric',''),
            'n_models':r.get('n_models',''),
            'blind_ids':r.get('blind_ids',''),
            'near_duplicate_count':len(set(rec)),
            'block_recurrence_count':len(blocks),
            'metric_recurrence_count':len(metrics),
            'source_type_recurrence_count':len(source_types),
            'near_duplicate_ids':';'.join(sorted(set(rec))),
        })
    out.sort(key=lambda r:(-int(r['block_recurrence_count']), -int(r['metric_recurrence_count']), r['catalogue_id']))
    return out


def collapse_catalogue(signif_rows, coh_rows):
    # Human catalogue: collapse near-duplicates by member-set Jaccard, prefer headline over watchlist and lower p.
    keep=[r for r in signif_rows if r['status'] in ('headline','watchlist')]
    keep.sort(key=lambda r:(r['status']!='headline', float(r['p_raw']), -int(r['n_models'])))
    groups=[]
    for r in keep:
        s=cluster_key_members(r)
        placed=False
        for g in groups:
            jac=len(s&g['members'])/len(s|g['members'])
            if jac >= 0.7:
                g['rows'].append(r); g['members'] |= s; placed=True; break
        if not placed:
            groups.append({'members':set(s), 'rows':[r]})
    return groups


def write_report(rows, feature_flags, signif, coh):
    groups=collapse_catalogue(signif, coh)
    bid_to_row={r['blind_id']:r for r in rows}
    headline_groups=[g for g in groups if any(r['status']=='headline' for r in g['rows'])]
    watch_groups=[g for g in groups if not any(r['status']=='headline' for r in g['rows'])]
    members_any=set().union(*(g['members'] for g in headline_groups)) if headline_groups else set()
    residual=[r for r in rows if r['blind_id'] not in members_any]
    # Special query helpers.
    early_grok={'grok-3','grok-4','grok-4-1-fast-non-reasoning','grok-4-1-fast-reasoning'}
    grok43='grok-4-3'
    late_anth={'opus-4-5','opus-4-6','opus-4-7','sonnet-4-6'}
    def models_for(g): return {model_label(bid_to_row[b]) for b in g['members'] if b in bid_to_row}
    early_hits=[g for g in headline_groups+watch_groups if len(models_for(g)&early_grok)>=3]
    grok43_hits=[g for g in headline_groups+watch_groups if grok43 in models_for(g) and len(models_for(g)&late_anth)>=2]
    path=OUT/'cluster_catalogue.md'
    with path.open('w', encoding='utf-8') as f:
        f.write('# Run 2 first-iteration cluster catalogue\n\n')
        f.write('Blind search; unblinded descriptions only. No new LLM/coder evaluations. First iteration excludes 2/3-feature subspace search.\n\n')
        f.write(f'- Headline subset: {len(rows)} models.\n')
        f.write(f'- Feature discontinuities flagged: {len(feature_flags)}.\n')
        f.write(f'- Density/nearest-neighbour candidates tested: {len(signif)} after exact de-duplication.\n')
        f.write(f'- Headline density rows: {sum(1 for r in signif if r["status"]=="headline")} (non-KNN, raw p<{HEADLINE_P}, FDR q<{HEADLINE_Q}).\n')
        f.write(f'- Watchlist density rows: {sum(1 for r in signif if r["status"]=="watchlist")}.\n')
        f.write(f'- KNN support rows, not headline claims: {sum(1 for r in signif if r["status"] in ("support","support_watch"))}.\n')
        f.write(f'- Collapsed headline member-sets: {len(headline_groups)}.\n')
        f.write(f'- Models in at least one headline cluster: {len(members_any)}.\n')
        f.write(f'- Diffuse residual under this search: {len(residual)} models.\n\n')
        f.write('## Methodological cautions\n\n')
        f.write('- `q_fdr` controls the many density-candidate tests in this first pass; feature discontinuity flags are descriptive scan results, not p-tested claims.\n')
        f.write('- KNN microclusters are used only as support/diagnostics, not as headline cluster claims; headline clusters require OPTICS or DBSCAN.\n')
        f.write('- The residual means "no small dense cluster under current features/search," not proof of psychological sameness.\n')
        f.write('- Lab composition below is descriptive after unblinding and was not used for search or significance.\n\n')
        f.write('## Headline collapsed clusters\n\n')
        if not headline_groups:
            f.write('No headline clusters survived FDR in this first iteration.\n\n')
        for gi,g in enumerate(headline_groups,1):
            reps=sorted(g['rows'], key=lambda r:(float(r['p_raw']), r['block']))
            best=reps[0]
            model_rows=[bid_to_row[b] for b in sorted(g['members']) if b in bid_to_row]
            labs=Counter(lab_label(r) for r in model_rows)
            f.write(f'### H{gi:02d} — n={len(g["members"])}; best {best["block"]}/{best["metric"]}; p={best["p_raw"]}; q={best["q_fdr"]}\n\n')
            f.write(f'- Members: ' + ', '.join(f'{model_label(r)} ({r["blind_id"]})' for r in model_rows) + '\n')
            f.write(f'- Lab composition: {dict(labs)}\n')
            f.write(f'- Source rows collapsed: {len(reps)}; blocks={sorted(set(r["block"] for r in reps))}; metrics={sorted(set(r["metric"] for r in reps))}\n')
            f.write(f'- Representative features/method: `{best.get("method","")}`; `{best.get("features","")[:300]}`\n\n')
        f.write('## Top feature discontinuities\n\n')
        f.write('| id | block | feature | side | n | gap | members | models |\n|---|---|---|---:|---:|---:|---|---|\n')
        for r in feature_flags[:40]:
            f.write(f"| {r['candidate_id']} | {r['block']} | `{r['feature']}` | {r['side']} | {r['n_models']} | {float(r['gap']):.4g} | {r['blind_ids']} | {r['UNBLINDING_METADATA_models']} |\n")
        f.write('\n## Worked predictions\n\n')
        f.write('### Early Grok\n\n')
        if early_hits:
            for g in early_hits[:10]:
                f.write('- Hit: ' + ', '.join(sorted(models_for(g))) + '\n')
        else:
            f.write('No headline/watchlist cluster contains at least three of the specified early-Grok set under this first-iteration search.\n')
        f.write('\n### Grok-4-3 with late Anthropic\n\n')
        if grok43_hits:
            for g in grok43_hits[:10]:
                f.write('- Hit: ' + ', '.join(sorted(models_for(g))) + '\n')
        else:
            f.write('No headline/watchlist cluster contains Grok-4-3 with at least two late-Anthropic models under this first-iteration search.\n')
        f.write('\n## Diffuse residual\n\n')
        f.write('Models not in any headline collapsed cluster under this search:\n\n')
        f.write(', '.join(f'{model_label(r)} ({r["blind_id"]})' for r in residual) + '\n')


def main():
    RANK_DIR.mkdir(parents=True, exist_ok=True)
    all_rows, rows = read_rows()
    cols = numeric_columns(rows, min_coverage=0.7)
    cols_by_block={b:block_columns(cols,b) for b in BLOCKS}

    feature_flags=discontinuity_scan(rows, cols)
    write_csv(OUT/'feature_discontinuity_catalogue.csv', feature_flags,
              ['candidate_id','source_type','block','feature','side','n_models','coverage_n','gap','column_sd','median_nonzero_gap','boundary_value','neighbor_value','blind_ids','UNBLINDING_METADATA_models'])

    # First iteration: no 2/3-feature subspace search; use full-block euclidean density + KNN microcluster search.
    candidates=density_candidates(rows, cols_by_block, metrics=('euclidean',))
    signif=significance_for_candidates(rows, candidates, cols_by_block)
    write_csv(OUT/'cluster_significance.csv', signif,
              ['candidate_id','source_type','block','metric','method','status','n_models','within_mean_distance','p_raw','q_fdr','feature_count','features','blind_ids','UNBLINDING_METADATA_models','UNBLINDING_METADATA_labs'])

    # Per-block density files include all rows for that block.
    for b in BLOCKS:
        br=[r for r in signif if r['block']==b]
        write_csv(OUT/f'density_clusters_{b}.csv', br,
                  ['candidate_id','source_type','block','metric','method','status','n_models','within_mean_distance','p_raw','q_fdr','feature_count','features','blind_ids','UNBLINDING_METADATA_models','UNBLINDING_METADATA_labs'])

    coh=coherence(signif, feature_flags)
    write_csv(OUT/'cluster_coherence_matrix.csv', coh,
              ['catalogue_id','status','block','metric','n_models','blind_ids','near_duplicate_count','block_recurrence_count','metric_recurrence_count','source_type_recurrence_count','near_duplicate_ids'])
    write_report(rows, feature_flags, signif, coh)

    print(f'Run-2 first iteration complete: {len(rows)} headline rows, {len(cols)} numeric cols')
    print(f'Feature discontinuities: {len(feature_flags)}')
    print(f'Density candidates tested: {len(signif)}; headline density rows: {sum(1 for r in signif if r["status"]=="headline")}')
    print(f'Wrote {OUT/"cluster_catalogue.md"}')

if __name__ == '__main__':
    main()
